start_time DateTime.civil(2020,5,28,0,0,0).to_time
warmup_duration 0.seconds
cooldown_duration 0.seconds

duration 1000.seconds
seeds \
	{communication_latencies 12345}
stats_print_interval 1

seed 12345

federation \
'{
	"resources": {
		"cluster1": {
			"cpu": "7000",
			"mem": "4096",
			"num_nodes": 1,
			"nodes": [
				{
					"node": "cluster1",
					"cpu": "7000",
					"mem": "4096"
				}
			]
		},
		"cluster2edge": {
			"cpu": "7000",
			"mem": "8192"
		},
		"cluster3edge": {
			"cpu": "7000",
			"mem": "8192"
		}
	},
	"latencies": [
		{
			"src": "cluster1",
			"dst": "cluster2edge",
			"value": "0.030"
		},
		{
			"src": "cluster1",
			"dst": "cluster3edge",
			"value": "0.050"
		}
	]
}'

customers \
    1 => { location_id: 0 }

workflow_types \
	1 => {
		component_sequence: [
			{
				name: "productpage",
				calls: [
					{ name: "details" },
					{
						name: "reviews",
						calls: [
							{ name: "ratings" }
						]
					}
				]
			}
		]
	}

request_gen \
	1 => {
		workflow_types: 1,
		starting_time: start_time,
		request_distribution: {distribution: :exponential, args: { rate: 0.01, seed: seed }},
		num_requests: 1,
		num_customers: 1
	}

microservice_types \
	"productpage" =>	{
		:service_time_distribution=>{
			:mec=> {distribution: :lognorm, args: {mu: -3.9863, sigma: 0.4237, seed: seed}},
			:cloud=>{:distribution=>:lognorm, :args=>{:mu=>-3.9863, :sigma=>0.4237, :seed=>12345}}
		},
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:node_affinity=>"local",
		:mdn_file=>"./mdn_models/productpage_weights.json",
		:rps=>30,
	},
	"reviews" =>	{
		:service_time_distribution=>{
			:mec=> {distribution: :lognorm, args: {mu: -5.7953, sigma: 0.66, seed: seed}},
			:cloud=>{:distribution=>:lognorm, :args=>{:mu=>-5.7953, :sigma=>0.66, :seed=>12345}}
		},
		:resources_requirements_cpu=>400,
		:resources_requirements_memory=>100,
		:mdn_file=>"./mdn_models/reviews_weights.json",
		:node_affinity=>"local",
		:rps=>30,
	},
	"ratings" =>	{
		:service_time_distribution=>{
			:mec=> {distribution: :lognorm, args: {mu: -7.2518, sigma: 0.4921, seed: seed}},
			:cloud=>{:distribution=>:lognorm, :args=>{:mu=>-7.2518, :sigma=>0.4921, :seed=>12345}}
		},
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:mdn_file=>"./mdn_models/ratings_weights.json",
		:node_affinity=>"local",
		:rps=>30,
	},
	"details" =>	{
		:service_time_distribution=>{
			:mec=> {distribution: :lognorm, args: {mu: -4.2602, sigma: 0.7735, seed: seed}},
			:cloud=>{:distribution=>:lognorm, :args=>{:mu=>-4.2602, :sigma=>0.7735, :seed=>12345}}
		},
		:mdn_file=>"./mdn_models/details_weights.json",
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:node_affinity=>"local",
		:rps=>30,
	}

services \
	'productpage' =>	{ serviceName: 'productpage', selector: 'productpage' },
	'reviews' =>	{ serviceName: 'reviews', selector: 'reviews' },
	'ratings' =>	{ serviceName: 'ratings', selector: 'ratings' },
	'details' =>	{ serviceName: 'details', selector: 'details' }

replica_sets \
	'app1' => { name: 'app1', selector: 'productpage', replicas: 1 },
	'app2' => { name: 'app2', selector: 'reviews', replicas: 3 },
	'app3' => { name: 'app3', selector: 'ratings', replicas: 3 },
	'app4' => { name: 'app4', selector: 'details', replicas: 3 }

evaluation \
cluster_hourly_cost: [
	{ cluster: :cluster1, fixed_cpu_hourly_cost: 0.100, fixed_memory_hourly_cost: 0.100 },
	{ cluster: :cluster2edge, fixed_cpu_hourly_cost: 0.100, fixed_memory_hourly_cost: 0.100 },
	{ cluster: :cluster3edge, fixed_cpu_hourly_cost: 0.100, fixed_memory_hourly_cost: 0.100 },
],

penalties: lambda {|general_stats, per_workflow_and_customer_stats|
	500.0 if general_stats.mean > 0.500
}
