start_time DateTime.civil(2020,5,28,0,0,0).to_time
warmup_duration 5.seconds
cooldown_duration 5.seconds

duration 30.seconds
seed 12345

federation \
'{
    "resources": {
        "europe-cloud-control-plane": {
            "cpu": "8000",
            "mem": "5984",
            "num_nodes": 1,
            "nodes": [
                {
                    "node": "europe-cloud-control-plane",
                    "cpu": "8000",
                    "mem": "5984"
                }
            ]
        }
    },
    "latencies": []
}'

customers \
    1 => { location_id: 0 }

workflow_types \
	1 => {
		component_sequence: [
			{ name: "productpage" },
			{ name: "reviews" },
			{ name: "ratings" },
		] 
	},
	2 => {
		component_sequence: [
			{ name: "productpage" },
			{ 
				type: "parallel",
				branches: [
					{ name: "reviews" },
					{ name: "details" }
				],
				wait_for: "all"
			},
			{ name: "ratings" }
		] 
	}

request_gen \
	1 => {
	    workflow_types: 2,
	    starting_time: start_time,
	    request_distribution: {distribution: :exponential, args: { rate: 5, seed: seed }},
	    num_requests: 10_000,
	    num_customers: 1
	}

microservice_types \
	"productpage" =>	{
		:service_time_distribution=>{
			:cloud=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}},
			:mec=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}}
		},
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:node_affinity=>"local",
		:max_processes=>4,
		:rps=>100
	},
	"reviews" =>	{
		:service_time_distribution=>{
			:cloud=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}},
			:mec=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}}
		},
		:resources_requirements_cpu=>400,
		:resources_requirements_memory=>100,
		:node_affinity=>"local",
		:max_processes=>2,
		:rps=>100
	},
	"ratings" =>	{
		:service_time_distribution=>{
			:cloud=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}},
			:mec=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}}
		},
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:node_affinity=>"local",
		:max_processes=>2,
		:rps=>100
	},
	"details" =>	{
		:service_time_distribution=>{
			:cloud=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}},
			:mec=>{:distribution=>:gaussian, :args=>{:mean=>0.015, :sd=>0.0015, :seed=>12345}}
		},
		:resources_requirements_cpu=>200,
		:resources_requirements_memory=>40,
		:node_affinity=>"local",
		:max_processes=>2,
		:rps=>100
	}

services \
	'productpage' =>	{
		serviceName: 'productpage',
		selector: 'productpage'
	},
	'reviews' =>	{
		serviceName: 'reviews',
		selector: 'reviews'
	},
	'ratings' =>	{
		serviceName: 'ratings',
		selector: 'ratings'
	},
	'details' =>	{
		serviceName: 'details',
		selector: 'details'
	}

replica_sets \
	'productpage-app' => {
		name: 'productpage-app',
		selector: 'productpage',
		replicas: 2
	},
	'reviews-app' => {
		name: 'reviews-app',
		selector: 'reviews',
		replicas: 2
	},
	'ratings-app' => {
		name: 'ratings-app',
		selector: 'ratings',
		replicas: 2
	},
	'details-app' => {
		name: 'details-app',
		selector: 'details',
		replicas: 2
	}

evaluation \
cluster_hourly_cost: [
    { cluster: :"europe-cloud-control-plane", fixed_cpu_hourly_cost: 0.100, fixed_memory_hourly_cost: 0.100 }
]
